/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GameInterfaces;

/**
 *
 * @author yeine
 */
public class AddingNumbersInterface extends javax.swing.JFrame {

    /**
     * Creates new form AddingNumbersInterface
     */
    public AddingNumbersInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AddingNumbers = new javax.swing.JLabel();
        tryAgain = new javax.swing.JButton();
        firstNumber = new javax.swing.JLabel();
        sign = new javax.swing.JLabel();
        secondNumber = new javax.swing.JLabel();
        sign2 = new javax.swing.JLabel();
        result = new javax.swing.JTextField();
        acertedSums = new javax.swing.JLabel();
        failedSums = new javax.swing.JLabel();
        totalSums = new javax.swing.JLabel();
        help = new javax.swing.JButton();
        solution = new javax.swing.JButton();
        finishGame = new javax.swing.JButton();
        sumsNumber = new javax.swing.JLabel();
        failedSumsNumber = new javax.swing.JLabel();
        totalSumsNumber = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AddingNumbers.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        AddingNumbers.setText("Sumando Números");

        tryAgain.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        tryAgain.setText("Otra vez");

        firstNumber.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        firstNumber.setText("jLabel1");

        sign.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        sign.setText("+");

        secondNumber.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        secondNumber.setText("jLabel1");

        sign2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        sign2.setText("=");

        result.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        result.setText("jTextField1");

        acertedSums.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        acertedSums.setText("Sumas acertadas");

        failedSums.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        failedSums.setText("Sumas no acertadas");

        totalSums.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        totalSums.setText("Total de sumas realizadas");

        help.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        help.setText("Ayuda");

        solution.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        solution.setText("Solucionar");

        finishGame.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        finishGame.setText("Terminar Juego");

        sumsNumber.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        sumsNumber.setText("jLabel1");

        failedSumsNumber.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        failedSumsNumber.setText("jLabel1");

        totalSumsNumber.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        totalSumsNumber.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(firstNumber)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sign)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(secondNumber)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sign2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(acertedSums)
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalSums)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(sumsNumber)
                                        .addGap(39, 39, 39)
                                        .addComponent(failedSums)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(failedSumsNumber)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tryAgain)
                                .addGap(80, 80, 80))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(solution)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(help)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(finishGame)
                        .addGap(71, 71, 71))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AddingNumbers))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(totalSumsNumber)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddingNumbers)
                    .addComponent(tryAgain))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sign)
                    .addComponent(secondNumber)
                    .addComponent(sign2)
                    .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(solution))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acertedSums)
                    .addComponent(failedSums)
                    .addComponent(sumsNumber)
                    .addComponent(failedSumsNumber))
                .addGap(33, 33, 33)
                .addComponent(totalSums)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalSumsNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(help)
                    .addComponent(finishGame))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddingNumbersInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddingNumbersInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddingNumbersInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddingNumbersInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddingNumbersInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddingNumbers;
    private javax.swing.JLabel acertedSums;
    private javax.swing.JLabel failedSums;
    private javax.swing.JLabel failedSumsNumber;
    private javax.swing.JButton finishGame;
    private javax.swing.JLabel firstNumber;
    private javax.swing.JButton help;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField result;
    private javax.swing.JLabel secondNumber;
    private javax.swing.JLabel sign;
    private javax.swing.JLabel sign2;
    private javax.swing.JButton solution;
    private javax.swing.JLabel sumsNumber;
    private javax.swing.JLabel totalSums;
    private javax.swing.JLabel totalSumsNumber;
    private javax.swing.JButton tryAgain;
    // End of variables declaration//GEN-END:variables
}
