/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GameInterfaces;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class Game2Interface extends javax.swing.JFrame {

    /**
     * Creates new form Game2Interface
     */
    public Game2Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        formingWords = new javax.swing.JLabel();
        randomWords = new javax.swing.JLabel();
        ingresedWord = new javax.swing.JTextField();
        toCorrectButton = new javax.swing.JButton();
        solveButton2 = new javax.swing.JButton();
        playerPoints = new javax.swing.JLabel();
        playerPointsNumber = new javax.swing.JLabel();
        helpButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        endGameButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        formingWords.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        formingWords.setText("Formando Palabras");

        randomWords.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        randomWords.setText("jLabel2");

        ingresedWord.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        ingresedWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresedWordActionPerformed(evt);
            }
        });

        toCorrectButton.setBackground(new java.awt.Color(0, 153, 153));
        toCorrectButton.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        toCorrectButton.setForeground(new java.awt.Color(0, 0, 0));
        toCorrectButton.setText("Corregir");

        solveButton2.setBackground(new java.awt.Color(0, 153, 153));
        solveButton2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        solveButton2.setForeground(new java.awt.Color(0, 0, 0));
        solveButton2.setText("Solucionar");
        solveButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solveButton2ActionPerformed(evt);
            }
        });

        playerPoints.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        playerPoints.setText("Puntaje:");

        playerPointsNumber.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        playerPointsNumber.setText("jLabel4");

        helpButton3.setBackground(new java.awt.Color(0, 153, 153));
        helpButton3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        helpButton3.setForeground(new java.awt.Color(0, 0, 0));
        helpButton3.setText("Ayuda");
        helpButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButton3ActionPerformed(evt);
            }
        });

        endGameButton2.setBackground(new java.awt.Color(0, 153, 153));
        endGameButton2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        endGameButton2.setForeground(new java.awt.Color(0, 0, 0));
        endGameButton2.setText("Terminar Juego");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 61, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(randomWords, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                                .addComponent(ingresedWord))
                            .addComponent(helpButton3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(playerPoints)
                                .addGap(18, 18, 18)
                                .addComponent(playerPointsNumber)))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addComponent(endGameButton2)
                            .addComponent(solveButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(toCorrectButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(formingWords)
                        .addGap(128, 128, 128))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(formingWords)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(randomWords, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ingresedWord, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(playerPoints)
                            .addComponent(playerPointsNumber))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(helpButton3)
                            .addComponent(jLabel5)
                            .addComponent(endGameButton2))
                        .addGap(27, 27, 27))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(toCorrectButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(solveButton2)
                        .addContainerGap(133, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresedWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresedWordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ingresedWordActionPerformed

    private void helpButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_helpButton3ActionPerformed

    private void solveButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solveButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_solveButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game2Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game2Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game2Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game2Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game2Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton endGameButton2;
    private javax.swing.JLabel formingWords;
    private javax.swing.JButton helpButton3;
    private javax.swing.JTextField ingresedWord;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel playerPoints;
    private javax.swing.JLabel playerPointsNumber;
    private javax.swing.JLabel randomWords;
    private javax.swing.JButton solveButton2;
    private javax.swing.JButton toCorrectButton;
    // End of variables declaration//GEN-END:variables
}
