package GameInterfaces;

/**
 *
 * @author Jasson, Yeiner y Edwin.
 */
import GameInterfaces.Game2Interface;
import GameInterfaces.AddingNumbersInterface;
import javax.swing.JFrame;

public class ProyectPrograInterface extends javax.swing.JFrame {

    /**
     * Creates new form ProyectPrograInterface
     */
    public ProyectPrograInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        proyectTitle = new javax.swing.JLabel();
        addingNumbersButton = new javax.swing.JButton();
        formingWordsButton = new javax.swing.JButton();
        helpButton1 = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));

        proyectTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        proyectTitle.setForeground(new java.awt.Color(0, 0, 0));
        proyectTitle.setText("IF2000 Proyect");

        addingNumbersButton.setBackground(new java.awt.Color(0, 153, 153));
        addingNumbersButton.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        addingNumbersButton.setForeground(new java.awt.Color(0, 0, 0));
        addingNumbersButton.setText("Adding Numbers");
        addingNumbersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addingNumbersButtonActionPerformed(evt);
            }
        });

        formingWordsButton.setBackground(new java.awt.Color(0, 153, 153));
        formingWordsButton.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        formingWordsButton.setForeground(new java.awt.Color(51, 51, 51));
        formingWordsButton.setText("Forming Words");
        formingWordsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formingWordsButtonActionPerformed(evt);
            }
        });

        helpButton1.setBackground(new java.awt.Color(0, 153, 153));
        helpButton1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        helpButton1.setForeground(new java.awt.Color(0, 0, 0));
        helpButton1.setText("Help");
        helpButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButton1ActionPerformed(evt);
            }
        });

        exitButton.setBackground(new java.awt.Color(0, 153, 153));
        exitButton.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        exitButton.setForeground(new java.awt.Color(0, 0, 0));
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(proyectTitle))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(addingNumbersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(formingWordsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(helpButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(proyectTitle)
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addingNumbersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formingWordsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitButton)
                    .addComponent(helpButton1))
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addingNumbersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addingNumbersButtonActionPerformed
        AddingNumbersInterface squareObject = new AddingNumbersInterface();
        squareObject.setSize(404, 326);
        squareObject.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        squareObject.setVisible(true); 
        squareObject.setLocationRelativeTo(null);
    }//GEN-LAST:event_addingNumbersButtonActionPerformed

    private void formingWordsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formingWordsButtonActionPerformed
        Game2Interface circleObject = new Game2Interface();
        
        circleObject.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        circleObject.setSize(494, 307); 
        circleObject.setVisible(true); 
        circleObject.setLocationRelativeTo(null);
    }//GEN-LAST:event_formingWordsButtonActionPerformed

    private void helpButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_helpButton1ActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProyectPrograInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProyectPrograInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProyectPrograInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProyectPrograInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProyectPrograInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addingNumbersButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton formingWordsButton;
    private javax.swing.JButton helpButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel proyectTitle;
    // End of variables declaration//GEN-END:variables
}
